##
# This workflow pushes helm charts to viadee/charts repository
##

name: Push vpw-polling-client-chart to viadee/charts repository

on:
  push:
    branches:
      - helm-charts
      - develop
      - master
    paths:
      - 'camunda-kafka-polling-client/deployment/helm/vpw-polling-client-chart/**'

jobs:
  update-chart-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout viadee/vPW repository
        uses: actions/checkout@v2
        with:
          path: polling-client

      - name: Checkout viadee/charts repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: viadee/charts
          path: charts

      #
      ## POLLING CLIENT
      #

      - name: Apply changes to viadee/charts repository - polling client
        run: |
          rm -rfv ./charts/charts/vpw-polling-client-chart
          cp -rv ./polling-client/camunda-kafka-polling-client/deployment/helm/vpw-polling-client-chart ./charts/charts/

      - name: Extract chart versions - polling client
        run: |
          helm show chart charts/charts/vpw-polling-client-chart > chart-infos-polling-client.txt
          version_polling_client=$( cat ./chart-infos-polling-client.txt | egrep "(version)(:)(\s)([0-9]+.[0-9]+.[0-9]+)" | egrep "([0-9]+.[0-9]+.[0-9]+)" -o)
          echo $version_polling-client
          echo "CHART_VERSION_POLLING_CLIENT=$version_polling_client" >> $GITHUB_ENV

      - name: Create pull request - polling client
        id: cpr-polling-client
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: ./charts
          base: main
          committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: "Update vpw-polling-client-chart to version ${{ env.CHART_VERSION_POLLING_CLIENT }}"
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: vpw-polling-client-chart-${{ env.CHART_VERSION_POLLING_CLIENT }}
          delete-branch: true
          title: vpw-polling-client-chart-${{ env.CHART_VERSION_POLLING_CLIENT }}
          body: "Update vpw-polling-client-chart to version ${{ env.CHART_VERSION_POLLING_CLIENT }}"
          draft: false
          labels: automated-created-pr

      - name: Check pull request - polling client
        run: |
          echo "Pull Request Number - ${{ steps.cpr-polling-client.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr-polling-client.outputs.pull-request-url }}"